name: peoplejob_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # 네트워킹 / 스토리지
  dio: ^5.8.0+1
  http: ^0.13.6
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.1

  # 에디터/파일
  flutter_quill: ^11.4.0
  flutter_quill_extensions: ^11.0.0
  file_picker: ^10.2.0
  image_picker: ^1.1.2

  # 아키텍처/라우팅
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.0

  # 환경/런처
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.1

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5

  # UI/유틸
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  cached_network_image: ^3.3.0
  permission_handler: ^11.1.0
  logger: ^2.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.3
  encrypt: ^5.0.1
  webview_flutter: ^4.11.0

dev_dependencies:
  # 기본 테스트
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # 통합 테스트
  integration_test:
    sdk: flutter

  # Mock / 코드생성
  mockito: ^5.4.4
  build_runner: ^2.4.9

  # 네트워크 모킹(Dio용)
  http_mock_adapter: ^0.6.1
  network_image_mock: ^2.1.1

  # 테스트 데이터/골든
  faker: ^2.1.0
  golden_toolkit: ^0.15.0

  # 코드 스타일/분석(선택)
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - test/fixtures/
    - test/golden_files/
